In [1]:
import numpy as np

## arange

In [2]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

## array

In [3]:
b = np.array([[1, 2, 3], [2, 4, 6]])
b

array([[1, 2, 3],
       [2, 4, 6]])

## linspace (1 ~ 10 分 6 等份)

In [4]:
test = np.linspace(1, 10, 6).reshape((2, 3))
test

array([[  1. ,   2.8,   4.6],
       [  6.4,   8.2,  10. ]])

## ndim / shape / size

In [5]:
print(b.ndim)
print(b.shape)
print(b.size)
isinstance(a, np.ndarray)

2
(2, 3)
6


True

## lambda

In [6]:
test_type = lambda x: type(x)

list(map(test_type, [a, b]))

[numpy.ndarray, numpy.ndarray]

## 基本矩陣運算

In [7]:
a*a

array([ 0,  1,  4,  9, 16, 25])

## 1D array => 2D array

In [8]:
a_2d = a[:, np.newaxis]
print('a shape: {}'.format(a.shape))
print('a_2d shape: {}'.format(a_2d.shape))
a_2d

a shape: (6,)
a_2d shape: (6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## 矩陣相乘（內積）

In [9]:
a_2d.T.dot(a_2d)

array([[55]])

## reshape

In [10]:
c = a.reshape((2, 3))
c

array([[0, 1, 2],
       [3, 4, 5]])

## zeros / ones / identity / inverse

In [11]:
print(np.zeros((3, 3)))

print(np.ones((3, 3)))

print(np.identity((3)))

print(np.linalg.inv(np.array([[0, 1], [2, 3]])))


[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[-1.5  0.5]
 [ 1.   0. ]]


## concatenate

In [12]:
row3 = np.arange(6, 9)
col4 = np.arange(98, 100).reshape((2, 1))
print(c, row3, col4, sep='\n', end='\n- - - -\n')

d = np.concatenate((c, [row3]), axis=0)
e = np.concatenate((c, col4), axis=1)
print(d, e, sep='\n')



[[0 1 2]
 [3 4 5]]
[6 7 8]
[[98]
 [99]]
- - - -
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2 98]
 [ 3  4  5 99]]


## stack / hstack / vstack

In [13]:
test = [[1, 2, 3], [4, 5, 6]]
print(np.stack((test), axis=0))
print(np.stack((test), axis=1), end='\n- - - -\n')

row3 = np.arange(6, 9)
col4 = np.arange(98, 100).reshape((2, 1))
print(row3, col4, sep='\n', end='\n- - - -\n')

d = np.vstack((c, row3))
e = np.hstack((c, col4))
print(d, e, sep='\n')

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
- - - -
[6 7 8]
[[98]
 [99]]
- - - -
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2 98]
 [ 3  4  5 99]]


## random.shuffle

In [14]:
print(d, end='\n- - - - -\n')
np.random.shuffle(d)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
- - - - -
[[6 7 8]
 [0 1 2]
 [3 4 5]]


## Boolean condition
- where
- isnan

In [15]:
print(d >= 5)
d[d>=5]

[[ True  True  True]
 [False False False]
 [False False  True]]


array([6, 7, 8, 5])

In [16]:
test = np.array([np.random.randint(10) for i in range(12)], dtype=np.float).reshape((4, 3))
test[test<3] = np.nan
print(test)
list(map(tuple, np.where(np.isnan(test))))

[[  9.  nan  nan]
 [ nan   7.  nan]
 [  5.   7.  nan]
 [ nan  nan  nan]]


[(0, 0, 1, 1, 2, 3, 3, 3), (1, 2, 0, 2, 2, 0, 1, 2)]

## sum / max / min /mean
- axis = 0 (每個 row 相加)
- axis = 1 (每個 col 相加)

In [17]:
print(d, end='\n - - - - - \n')

print(np.sum(d, axis=0), end='\n - - - - - \n')
print(np.sum(d, axis=1), end='\n - - - - - \n')

print(np.max(d, axis=0), end='\n - - - - - \n')

print(np.min(d, axis=1), end='\n - - - - - \n')

print(np.mean(d, axis=1))

[[6 7 8]
 [0 1 2]
 [3 4 5]]
 - - - - - 
[ 9 12 15]
 - - - - - 
[21  3 12]
 - - - - - 
[6 7 8]
 - - - - - 
[6 0 3]
 - - - - - 
[ 7.  1.  4.]
