# Numpy（基於底層語言之矩陣運算）
- axis = 0：列 row
- axis = 1：行 column

In [1]:
import numpy as np

## Build matrix
- array
- zeros
- ones

In [2]:
# ndarray

a = np.array([[1, 2, 3],  [2, 3, 4]], dtype=np.int)
b = np.array([[1, 2, 3],  [2, 3, 4]], dtype=np.float)

print(a, b, sep='\n')
print('','dtype : ', a.dtype, '\n', 'dtype : ', b.dtype)
print('dim : ', a.ndim)
print('shape : ', a.shape)
print('size : ', a.size)

isinstance(a, np.ndarray)

[[1 2 3]
 [2 3 4]]
[[ 1.  2.  3.]
 [ 2.  3.  4.]]
 dtype :  int64 
 dtype :  float64
dim :  2
shape :  (2, 3)
size :  6


True

In [3]:
# build from list

a = [1, 3, 5, 7, 9, 11]
b = np.array(a).reshape((2, 3))
b

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [4]:
# identity

a = np.identity((3))
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
# zeros

a = np.zeros((3, 4))
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
# ones

b = np.ones((3, 4), dtype=np.float16)
b

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], dtype=float16)

## 產生數列
- arange
- linspace

In [7]:
# arange（類似 python 的 range）

a = np.arange(0, 24, 2).reshape((3, 4))
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
# 1 ~ 10 間的數列，區間：(10-1)/5 = 1.8

a = np.linspace(1, 10, 6).reshape((2, 3))
a

array([[  1. ,   2.8,   4.6],
       [  6.4,   8.2,  10. ]])

In [9]:
# 隨機產生

a = np.random.random((2, 3))
a

array([[ 0.22347359,  0.81053323,  0.10184289],
       [ 0.70951969,  0.9807054 ,  0.04644175]])

## 合併 array
- concatenate

In [10]:
a = np.arange(6).reshape((2, 3))
b = np.arange(3).reshape((1, 3))
c = np.zeros((2, 1), dtype=np.int)
print('a : ', a, sep='\n')
print('b : ', b, sep='\n')
print('c : ', c, sep='\n', end='\n\n')

# 合併 by row

print(np.concatenate((a, b), axis=0), end='\n\n')

# 合併 by column

print(np.concatenate((a, c), axis=1))

a : 
[[0 1 2]
 [3 4 5]]
b : 
[[0 1 2]]
c : 
[[0]
 [0]]

[[0 1 2]
 [3 4 5]
 [0 1 2]]

[[0 1 2 0]
 [3 4 5 0]]


## 取值

In [11]:
# 1-D array

a = np.arange(6)
a[1]

1

In [12]:
# 2-D array

a = np.arange(25).reshape((5, 5))
print(a)
print(a[2, -1])
print(a[1:3, 1:5:2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
14
[[ 6  8]
 [11 13]]


## 條件控制

In [13]:
b = np.arange(16, dtype=np.int).reshape((4, 4))
print(b)
b[(2<b)&(b<13)] = 0
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0 13 14 15]]


## 矩陣基本運算

In [14]:
# 一般減法

a = np.array([[1, 2, 3],  [2, 3, 4]], dtype=np.int)
b = np.ones(3, dtype=np.int)

print(a, b, sep='\n\n', end='\n\n')
print(a-b, end='\n\n')
print(a-1)

[[1 2 3]
 [2 3 4]]

[1 1 1]

[[0 1 2]
 [1 2 3]]

[[0 1 2]
 [1 2 3]]


- 一般乘法 v.s 矩陣乘法

In [15]:
# 一般乘法

a = np.array([[1, 2, 3],  [2, 3, 4]], dtype=np.int)
c = 10*np.sin(a)
print(c)

[[ 8.41470985  9.09297427  1.41120008]
 [ 9.09297427  1.41120008 -7.56802495]]


In [16]:
# 一般乘法 v.s 矩陣乘法

a = np.array([[1, 2],  [2, 3]], dtype=np.int)
b = np.arange(4).reshape((2, 2))
print(a, b, sep='\n\n', end='\n\n')
print(a*b, end='\n\n')
print(np.dot(a, b))

[[1 2]
 [2 3]]

[[0 1]
 [2 3]]

[[0 2]
 [4 9]]

[[ 4  7]
 [ 6 11]]


In [17]:
# sum、min、max

a = np.random.random((2, 3))
print(a, end='\n\n')
print(np.sum(a))   # all
print(np.sum(a, axis=1))   # row
print(np.sum(a, axis=0))   # column
print(np.min(a))
print(np.max(a))

[[ 0.46318622  0.9580061   0.36259841]
 [ 0.0643395   0.03595779  0.54732966]]

2.43141767967
[ 1.78379072  0.64762696]
[ 0.52752572  0.99396389  0.90992807]
0.0359577895171
0.958006095742


## 線性代數運算

In [18]:
a = np.array([[0, 1],
                   [2, 3]])
a

array([[0, 1],
       [2, 3]])

In [19]:
# transpose

a.T

array([[0, 2],
       [1, 3]])

In [20]:
# inverse

inv = np.linalg.inv(a)
inv

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [21]:
# dot 內積

np.dot(a, inv)

array([[ 1.,  0.],
       [ 0.,  1.]])

## Vector stacking

In [22]:
a = np.array([[0, 1], 
                   [2, 3]])
b = np.array([[4, 5], 
                   [6, 7]])
c = np.array([[8, 9], 
                   [10, 11]])

In [23]:
# vertical

v = np.vstack((a, b ,c))
print(v.shape)
v

(6, 2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
# horizontal

h = np.hstack((a, b ,c))
print(h.shape)
h

(2, 6)


array([[ 0,  1,  4,  5,  8,  9],
       [ 2,  3,  6,  7, 10, 11]])

In [25]:
# stack：axis=0

s = np.stack((a, b, c), axis=0)
print(s.shape)
s

(3, 2, 2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [26]:
# stack：axis=1

s = np.stack((a, b, c), axis=1)
print(s.shape)
s

(2, 3, 2)


array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])